# Generated by Django 4.2.5 on 2023-09-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='type',
            field=models.CharField(choices=[('by taske', 'by taske'), ('part time', 'part time'), ('full time', 'full time'), ('other', 'other')], default='fulltime', max_length=50),
        ),
    ]
