# Generated by Django 4.2.5 on 2023-09-19 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=5000)),
                ('category', models.CharField(max_length=20)),
                ('country', models.CharField(blank=True, max_length=15, null=True)),
                ('cite', models.CharField(blank=True, max_length=15, null=True)),
                ('image', models.FileField(default='img\\post.png', upload_to='jobs/image')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('trend', models.BooleanField(default=True)),
                ('approve', models.BooleanField(default=False)),
                ('link', models.URLField(blank=True, null=True)),
                ('applyed', models.BooleanField(default=False)),
                ('auther', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
