# Generated by Django 4.2.5 on 2023-09-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_jobs_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='type',
            field=models.CharField(choices=[('other', 'other'), ('part time', 'part time'), ('full time', 'full time'), ('by taske', 'by taske')], default='full time', max_length=50),
        ),
    ]
