# Generated by Django 4.2.5 on 2023-09-19 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_jobs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fitures',
            new_name='Features',
        ),
    ]
