# Generated by Django 4.2.5 on 2023-09-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_jobs_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='type',
            field=models.CharField(choices=[('full time', 'full time'), ('other', 'other'), ('by taske', 'by taske'), ('part time', 'part time')], default='full time', max_length=50),
        ),
    ]
