# Generated by Django 4.2.5 on 2023-09-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_jobs_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='type',
            field=models.CharField(choices=[('part time', 'part time'), ('by taske', 'by taske'), ('other', 'other'), ('full time', 'full time')], default='full time', max_length=50),
        ),
    ]
