# Generated by Django 4.2.5 on 2023-09-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_bio_alter_jobs_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='type',
            field=models.CharField(choices=[('full time', 'full time'), ('part time', 'part time'), ('by taske', 'by taske'), ('other', 'other')], default='fulltime', max_length=50),
        ),
    ]
