# Generated by Django 4.2.5 on 2023-09-19 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_jobs_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.FileField(default=django.utils.timezone.now, upload_to='categoies/image'),
            preserve_default=False,
        ),
    ]
