# Generated by Django 4.2.5 on 2023-09-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='time',
            field=models.CharField(choices=[('on site', 'on site'), ('remotly ', 'remotly '), ('other', 'other')], default='on site', max_length=50),
        ),
        migrations.AddField(
            model_name='jobs',
            name='type',
            field=models.CharField(choices=[('other', 'other'), ('by taske', 'by taske'), ('full time', 'full time'), ('part time', 'part time')], default='fulltime', max_length=50),
        ),
    ]
