# Generated by Django 4.2.5 on 2023-09-20 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_jobs_time_jobs_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='location',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='slary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='tage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='type',
            field=models.CharField(choices=[('part time', 'part time'), ('full time', 'full time'), ('by taske', 'by taske'), ('other', 'other')], default='fulltime', max_length=50),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile/profiles')),
                ('cover', models.ImageField(upload_to='profile/covers')),
                ('location', models.URLField()),
                ('campany', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
