# Generated by Django 4.2.4 on 2023-09-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_jobs_location_jobs_slary_jobs_tage_alter_jobs_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='location',
            field=models.URLField(blank=True, default='world', null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='type',
            field=models.CharField(choices=[('other', 'other'), ('by taske', 'by taske'), ('part time', 'part time'), ('full time', 'full time')], default='fulltime', max_length=50),
        ),
    ]
