# Generated by Django 4.2.4 on 2023-09-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_jobs_location_alter_jobs_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='number_of_view',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobs',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='type',
            field=models.CharField(choices=[('other', 'other'), ('full time', 'full time'), ('by taske', 'by taske'), ('part time', 'part time')], default='fulltime', max_length=50),
        ),
    ]
