# Generated by Django 4.2.5 on 2023-09-20 20:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_jobs_number_of_view_jobs_rating_alter_jobs_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AddField(
            model_name='jobs',
            name='content',
            field=ckeditor.fields.RichTextField(default=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobs',
            name='type',
            field=models.CharField(choices=[('by taske', 'by taske'), ('full time', 'full time'), ('part time', 'part time'), ('other', 'other')], default='fulltime', max_length=50),
        ),
    ]
